### PR TITLE
Update hawkeye_apis.py

### PR DESCRIPTION
**Pull request by ditekshen**

### CODE REVIEW

**Comment by doomedraven** [comment]
hey thanks a lot for this, i have small suggestion, as we don't have anymore full control of this repo, could you push new stuff here https://github.com/kevoreilly/CAPE/ it would speedup merges

**Comment by ditekshen** [comment]
I didn't know that. Will do so from now on.

**Comment by doomedraven** [comment]
thanks

**Comment by kevoreilly** [comment]
Any chance you could supply some example hashes? There is a HawkEye payload sig - if it's not firing on the same samples I will try and update it.

**Comment by ditekshen** [comment]
Here is a sample: e4b4a93dc889952a88ac8b37561f5160ce341586cd582623abc493978dbd55a0

**Pull request merged**
