### PR TITLE
Adding loop detection capability

### PR DESCRIPTION
**Pull request by mabj**
Hi folks from CAPE, 

this change adds log (BSON) compression by detecting loops in the logs exported by the monitor. This update enables the following improvements:
 * reduces size of BSONs in disk;
 * reduces size of final JSON report exported to users;
 * reduces the size of the main task structure import to Mongo;
 * speed-up searches in the UI since there is less data; and
 * makes behaviour report easier to read.

I wrote more about this change in this blogpost:
<pre>
http://security.neurolabs.club/2019/12/inline-loop-detection-for-compressing.html
</pre>

cheers,
Marcos

### CODE REVIEW

**Comment by kevoreilly** [comment]
Wow fantastic - thank you very much!

**Comment by doomedraven** [comment]
xD dude you should ping me in pm, v1 is dead :P but thanks

**Comment by doomedraven** [comment]
Marcos i have integrated it to v2 https://github.com/kevoreilly/CAPEv2/commit/809f0b67a14fadd72cc7191dd3e24ffbb716a60b

v1 is end of life

**Comment by mabj** [comment]
Oh, nice! I'm forking v2 right now :) Thanks, @doomedraven!

**Comment by mabj** [comment]
But since the Merge Request is here and it is just a matter of pressing the "merge" button. Don't you think it is a good idea to also add this to CAPE v1? I bet there is still some people relying on v1 around.

**Comment by kevoreilly** [comment]
Agreed :)

**Comment by mabj** [comment]
Thanks, @kevoreilly :}

**Pull request merged**
