### PR TITLE
Update cryptopools.py

### PR DESCRIPTION
**Pull request by bartblaze**
Add more pools. Hope this is useful, cc @doomedraven

### CODE REVIEW

**Comment by doomedraven** [comment]
nice stuff, thanks :)

**Comment by doomedraven** [comment]
Kevin is afk this days so there will be small delays on merges

**Comment by bartblaze** [comment]
Thanks doomedraven! I also just noticed there was a wrong commit in this one, deleted. Will wait for Kev to merge :smiley:

**Comment by kevoreilly** [comment]
Thanks Bart! 

Any reason not to add the sig too? I held off merging only because a cape_type field is needed for proper display in the ui, and I am in Thailand so only have my phone, I can't really test or edit anything.

**Comment by bartblaze** [comment]
My pleasure! Yeah, that was a commit to a wrong repo. I'll likely create a new PR where I'll add some Yara rules that can be useful - will be over the next few days or so. Will make sure to add the _cape_type_ field.

Happy travels!

**Pull request merged**
