### PR TITLE
Add remcos artificats signatures

### PR DESCRIPTION
**Pull request by ditekshen**
Adding 3 signatures for detecting remcos artifacts including created mutexes, registry keys, and files.

### CODE REVIEW

**Comment by doomedraven** [comment]
wouldn't it be better to just put that 3 signatures in the same files lets say remcos.py and have all in 1 ? :)

**Comment by ditekshen** [comment]
I thought of that initially, but then realized that the displayed description and associated data won't appear as descriptive or comprehensive. I am open for suggestions.

**Comment by doomedraven** [comment]
how? the description is from the description field

**Comment by ditekshen** [comment]
Correct. However, not all of the tested samples exhibited the same behavior as far as I can tell, for example, some created the mutexes but not the registry keys. The separation of the files was also to highlight what artifacts were actually created.

**Comment by doomedraven** [comment]
ah ok you didn't get me i think

if you but 3 signatures in 1 file, oyu need to keep them with their classes, so it will be really 3 diff signatures and they will match correct description like this

```
# Copyright (C) 2019 ditekshen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from lib.cuckoo.common.abstracts import Signature

class RemcosFiles(Signature):
    name = "remcos_files"
    description = "Creates known Remcos directories and/or files"
    severity = 3
    categories = ["RAT"]
    families = ["Remcos"]
    authors = ["ditekshen"]
    minimum = "0.5"

    def run(self):
        remcos_files = False

        indicators = [
            ".*\\\\AppData\\\\Roaming\\\\remcos\\\\",
            ".*\\\\AppData\\\\Roaming\\\\remcos\\\\logs\.dat$",
        ]

        for indicator in indicators:
            file_match = self.check_file(pattern=indicator, regex=True)
            if file_match:
                for match in file_match:
                    self.data.append({"file": match})
                remcos_files = True

        return remcos_files 


class RemcosMutexes(Signature):
    name = "remcos_mutexes"
    description = "Creates known Remcos mutexes"
    severity = 3
    categories = ["RAT"]
    families = ["Remcos"]
    authors = ["ditekshen"]
    minimum = "0.5"

    def run(self):
        indicators = [
            "Remcos_Mutex_Inj",
            "Remcos-[A-Z0-9]{6}$",
        ]

        for indicator in indicators:
            if self.check_mutex(pattern=indicator, regex=True):
                return True

        return False

class RemcosRegkeys(Signature):
    name = "remcos_regkeys"
    description = "Creates known Remcos registry keys"
    severity = 3
    categories = ["RAT"]
    families = ["Remcos"]
    authors = ["ditekshen"]
    minimum = "0.5"

    def run(self):
        remcos_keys = False

        indicators = [
            ".*\\\\Software\\\\Remcos-[A-Z0-9]{6}.*",
        ]

        for indicator in indicators:
            match = self.check_key(pattern=indicator, regex=True)
            if match:
                self.data.append({"Key": match})
                remcos_keys = True

        return remcos_keys 
```

**Comment by ditekshen** [comment]
Ah, I see now. That makes sense. Testing now.

**Comment by ditekshen** [comment]
Done, all 3 files have been merged into 1 file. Thank you for the suggestion.

**Comment by doomedraven** [comment]
you are welcome, thanks for the colaboration!

**Pull request merged**
