### PR TITLE
Add packers signatures

### PR DESCRIPTION
**Pull request by ditekshen**

### CODE REVIEW

**Comment by doomedraven** [comment]
nice, one small thing, you can simplify a lot code doing stuff like this

`for section in self.results.get("static", {}).get("pe", {}).get("sections", []):`

**Comment by doomedraven** [comment]
example:

```
    def run(self):
        for section in self.results.get("static", {}).get("pe", {}).get("sections", []):
            if section["name"].lower().startswith(".aspack"):
                self.data.append({"section" : section})
                return True

        return False 
```

**Comment by ditekshen** [comment]
Thanks for the suggestion and the example! Will definitely consider it for future signatures in this category.

**Comment by doomedraven** [comment]
thanks for simplification :)

**Comment by ditekshen** [comment]
Had spare time to implement and test the example you provided. Thank you for the suggestion!

**Comment by doomedraven** [comment]
always welcome :)

**Comment by kevoreilly** [comment]
This is awesome thank you.

**Pull request merged**
