### PR TITLE
Fix file resubmission path

### PR DESCRIPTION
**Pull request by enzok**

### CODE REVIEW

**Comment by kevoreilly** [comment]
Thank you

**Comment by doomedraven** [comment]
em that is the same no?

```
if opt_filename:
                    filename = base_dir + "/" + opt_filename
                else:
                    filename = base_dir + "/" + resubmission_hash
```

**Comment by kevoreilly** [comment]
I did notice this doesn't work on public instance, suspected there was an issue. I can't test this fixes it until later though.

**Comment by doomedraven** [comment]
weird, well hope that fix it

**Pull request merged**
