### PR TITLE
Added mongodb authentication feature

### PR DESCRIPTION
**Pull request by elmaisbuscado**

### CODE REVIEW

**Comment by doomedraven** [comment]
looks good so far

**Comment by kevoreilly** [comment]
Thank you elmaisbuscado for this PR - I'll try and find a way to get it tested and merged.

**Comment by kevoreilly** [comment]
Still not found suitable testing for this.

**Comment by doomedraven** [comment]
i ahve it in production without auth enabled, and no problems

**Comment by kevoreilly** [comment]
With @doomedraven having it in production without problems, and no obvious test candidates, I'm going to merge and rely on any problems with this PR to come to light.

**Pull request merged**
