### PR TITLE
FLOSS integration

### PR DESCRIPTION
**Pull request by marirs**
FireEye FLOSS integration

### CODE REVIEW

**Comment by doomedraven** [comment]
nice, but can it be optional? maybe apart of path add enable_floss = yes/no

**Comment by kevoreilly** [comment]
Yeah I agree we should make it optional/configurable

**Comment by marirs** [comment]
Sure, I'll make an "yes/no" option. For now, if floss is not found in the said path or not available, it will fall back to original strings.

 Is it okay for me to do the yes/no option in another next pull... and you merge this.. I'm a little awkward with this Git thing.. :D

**Comment by doomedraven** [comment]
you can select change to your dev branch ` git checkout dev` and do changes, and pr it :)

**Comment by marirs** [comment]
Oh - ok... So that will be another PR right?

**Comment by doomedraven** [comment]
that would be in the same PR just another commit

**Comment by marirs** [comment]
Ok.. Will try it then... :D 
Thanks for the tip :)

**Comment by doomedraven** [comment]
you are welcome :)

**Comment by marirs** [comment]
hooray.. getting the hang of git :D 
added 2 more config keys
1) enable or disable floss from processing.conf
2) you can also mention upto how much file size (in mb) you would like floss to extract strings.

**Comment by doomedraven** [comment]
@marirs  congrats :) can you please check why there is conflict in ? `web/templates/analysis/CAPE/index.html`

**Comment by marirs** [comment]
Ok.. looks like the conflict is resolved....

**Pull request merged**
