### PR TITLE
update description of vtdl

### PR DESCRIPTION
**Pull request by doomedraven**
i figurated what many user doesn't know about this feature what you can pass to vtdl hash,hash,hash, so i hope that will help them

### CODE REVIEW

**Comment by doomedraven** [comment]
Nop, that only do it for coma separated, not even coma and space i will add strip later to handle coma and space cases as i have rewrote the code of downloading so adding external services now is only few lines

**Comment by kevoreilly** [comment]
But any whitespace separarors including multiple spaces, tabs and new lines can be pasted straight into the field. But I guess it has to be whitespace or commas, not both.

**Comment by doomedraven** [comment]
right now
```
hashlist = []
if "," in vtdl:
      hashlist=vtdl.split(",")
else:
      hashlist.append(vtdl)
```


i will improve it with another PR

**Comment by kevoreilly** [comment]
Looks like your snippet is from web\api\views.py but mine is from web\submission\views.py - I can replicate this code in the api too?

**Comment by doomedraven** [comment]
yes go for it :)

**Comment by doomedraven** [comment]
but be careful with empty split

**Comment by kevoreilly** [comment]
Will change to else: hashlist=vtdl.replace(" ", "").strip()

**Comment by doomedraven** [comment]
this is what i mean
```
>>> vtdl = "hash1 hash2"
>>> vtdl.replace(" ", "").strip()
'hash1hash2'
```

**Comment by kevoreilly** [comment]
Ah yeah that's no good!

**Pull request merged**
