### PR TITLE
Full network data removal from filtered dns.

### PR DESCRIPTION
**Pull request by redsand**
Fixes error where not all network data is removed from all streams.

### CODE REVIEW

**Comment by doomedraven** [comment]
small suggestion why to not to put the `for delip in self.ip_whitelist:` out of 4 loops, and do a big one, and use thing like .items() etc to match `if x in z`, would simplify code and remove so many loops no?

**Comment by redsand** [comment]
I was actually looking for a way to do that and my python fu isn’t that great. 

I’m a c developer at heart and use python to sketch and model code for c. 

Could you show me an example method?

Tim

Sent from my iPhone

On Sep 17, 2018, at 9:29 AM, doomedraven <notifications@github.com> wrote:

small suggestion why to not to put the for delip in self.ip_whitelist: out of 4 loops, and do a big one, and use thing like .items() etc to match if x in z, would simplify code and remove so many loops no?

**Comment by doomedraven** [comment]
Yeñ i will help you later

**Comment by doomedraven** [comment]
for example

```
        if enabled_whitelist:
            
            for delip in self.ip_whitelist:
                for host in self.results["hosts"]:
                    if delip == host["ip"]:
                        self.results["hosts"].remove(host)
                for host in self.results["tcp"]:
                    if delip == host["src"] or delip == host["dst"]:
                        self.results["tcp"].remove(host)
                for host in self.results["udp"]:
                    if delip == host["src"] or delip == host["dst"]:
                        self.results["udp"].remove(host)
                for host in self.results["icmp"]:
                    if delip == host["src"] or delip == host["dst"]:
                        self.results["icmp"].remove(host)
```

**Comment by doomedraven** [comment]
and even as they are dict you can do

```
>>> a = {1:2,3:4,5:6,7:8}
>>> a.values()
[2, 4, 6, 8]
```

```
        if enabled_whitelist:
            
            for delip in self.ip_whitelist:
                 if delip in self.results["hosts"].values():
                          self.results["hosts"].remove(self.results["hosts"].keys()[self.results["hosts"].values().index(delip)])
 
```

**Comment by redsand** [comment]
Hi,

This method still loops through each at the same amount except it also copies the data into memory rather than iterating it. 

It also increases the comparison count. 

Is this a performance increase? 

Tim

On Sep 17, 2018, at 12:28 PM, doomedraven <notifications@github.com> wrote:

and even as they are dict you can do

>>> a = {1:2,3:4,5:6,7:8}
>>> a.values()
[2, 4, 6, 8]
        if enabled_whitelist:
            
            for delip in self.ip_whitelist:
                 if delip in self.results["hosts"].values():
                          self.results["hosts"].remove(self.results["hosts"].keys()[self.results["hosts"].values().index(delip)])

**Comment by doomedraven** [comment]
its kinda similar :) so it's up to you

**Comment by redsand** [comment]
I'm open to the change, but would like to see this bake in first to see if there are any issues with the current solution. That ok?

**Comment by doomedraven** [comment]
fixed on my side :) pr is coming, basically there was few erros
so FYI
where you was getting remote from options default was "no", should be False
there was `"("]+bpf.split()+[")" should be "(", bpf, ")"`
and few more

**Comment by doomedraven** [comment]
so @redsand if my pr will breaks your stuff, make sure to log.info(str(pargs)) so you can see how it executed

**Comment by redsand** [comment]
Hi, this push fixes all errors on my end.  Including the ones with sniffer and the updated code for network whitelist.

@doomedraven can you review?  I think our sniffers look almost the same but it looked off from last night.

**Comment by doomedraven** [comment]
great, yes secodn

**Comment by doomedraven** [comment]
@kevoreilly i can confirm, sniffer back to life with changes here

**Comment by kevoreilly** [comment]
Awesome thanks guys

**Pull request merged**
