### PR TITLE
fix sniffer.py

### PR DESCRIPTION
**Pull request by doomedraven**
@kevoreilly @redsand please test it, 

@kevoreilly merge another PR as there is a small fix for my indent issue in abstracts

### CODE REVIEW

**Comment by doomedraven** [comment]
i have tested it in local and now im able to capture traffic again in with local sniffer

**Comment by doomedraven** [comment]
@redsand note changes
`pargs.extend(["'", "host", host])` become `pargs.extend(["host", host])` as in original
and at the end there useless `pargs.extend(["'"])`

so apart of that it should works for remote

**Comment by redsand** [comment]
Fails on my end:
`WARNING:lib.cuckoo.core.plugins:Unable to start auxiliary module sniffer: Command '['ssh', 'root@192.168.122.1', 'nohup', '/bin/bash', '/tmp/3545.sh', '>', '/tmp/log', '2>', '/tmp/err']' returned non-zero exit status 2
2018-09-17 20:50:15,326 [lib.cuckoo.core.plugins] WARNING: Unable to start auxiliary module sniffer: Command '['ssh', 'root@192.168.122.1', 'nohup', '/bin/bash', '/tmp/3545.sh', '>', '/tmp/log', '2>', '/tmp/err']' returned non-zero exit status 2`

I believe its your change of the extend.  I recall needing that line to be sent as a string, not an array of items.

**Comment by doomedraven** [comment]
well that is easy to fix, you just need to investigate where, and do " ".join(pargs) `if remote` bcz that was breaking local sniffer

**Comment by doomedraven** [comment]
second i restored your stuff under ifs, testing if local doesn't broke again

**Comment by doomedraven** [comment]
@redsand check now

**Comment by redsand** [comment]
here is a version that works for me as well
https://github.com/redsand/CAPE/tree/sniff2

**Comment by doomedraven** [comment]
testing update on my side will pr if not breaks

**Comment by doomedraven** [comment]
updated, @redsand can you test it?

**Comment by redsand** [comment]
oops, another bug.  stand by.  Looks like the remote destination path should't be the same as the local destination path.

`INFO:modules.auxiliary.sniffer:Started sniffer with PID 6753 (interface=br0, host=192.168.122.152, dump path=/home/cuckoo/CAPE/storage/analyses/3035/dump.pcap)
2018-09-17 21:11:15,395 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6753 (interface=br0, host=192.168.122.152, dump path=/home/cuckoo/CAPE/storage/analyses/3035/dump.pcap)`

`
WARNING:modules.processing.network:The PCAP file does not exist at path "/home/cuckoo/CAPE/storage/analyses/2959/dump.pcap".
2018-09-17 21:07:41,885 [modules.processing.network] WARNING: The PCAP file does not exist at path "/home/cuckoo/CAPE/storage/analyses/2959/dump.pcap".
`

**Comment by doomedraven** [comment]
but they are
```
if remote:
            file_path = "/tmp/tcp.dump.%d" % self.task.id
        else:
            file_path = os.path.join(CUCKOO_ROOT, "storage", "analyses","%s" % self.task.id, "dump.pcap")
```

**Comment by doomedraven** [comment]
or that is on stop?

```
file_path = os.path.join(CUCKOO_ROOT, "storage", "analyses",
                                 "%s" % self.task.id, "dump.pcap")
             file_path2 = "/tmp/tcp.dump.%d" % self.task.id

             remote_output = subprocess.check_output([ 'scp', '-q', remote_host + ":" + file_path2, file_path ], stderr=DEVNULL)
             remote_output = subprocess.check_output([ 'ssh', remote_host, 'rm', '-f', file_path2 ], stderr=DEVNULL)
```

**Comment by redsand** [comment]
Here's your gap in this PR and what's working on my end.

`cuckoo@cape-01:~$ diff -uN sniffer.py sniffer2.py
--- sniffer.py  2018-09-17 21:34:28.766113006 +0000
+++ sniffer2.py 2018-09-17 21:35:06.637637876 +0000
@@ -31,7 +31,7 @@
         if remote:
             file_path = "/tmp/tcp.dump.%d" % self.task.id
         else:
-            file_path = os.path.join(CUCKOO_ROOT, "storage", "analyses", str(self.task.id), "dump.pcap")
+            file_path = os.path.join(CUCKOO_ROOT, "storage", "analyses","%s" % self.task.id, "dump.pcap")
         host = self.machine.ip
         # Selects per-machine interface if available.
         if self.machine.interface:
@@ -104,11 +104,14 @@
                       "not", "(", "src", "host", resultserver_ip, "and",
                       "src", "port", resultserver_port, ")"])

-        if remote and bpf:
-            pargs.extend(["and", "("] + bpf.split(' ') + [ ")" ] )
+        if bpf:
+            if remote:
+                pargs.extend(["and", "("] + bpf.split(' ') + [ ")" ] )
+            else:
+                pargs.extend(["and", "(", bpf, ")" ] )
+
+        if remote:
             pargs.extend(["'"])
-        elif bpf:
-            pargs.extend(["and", "(", bpf, ")"])

         if remote and not remote_host:
             log.exception("Failed to start sniffer, remote enabled but no ssh string has been specified")
`

**Comment by doomedraven** [comment]
it's all there, nto make sense check twice bpf no? the rest is the same

```
        if bpf:
            if remote:
                pargs.extend(["and", "("] + bpf.split(' ') + [ ")" ] )
            else:
                pargs.extend(["and", "(", bpf, ")" ] )

        if remote:
            pargs.extend(["'"])

```

**Comment by redsand** [comment]
Nope, not the same... can see diff


On Sep 18, 2018, at 12:28 AM, doomedraven <notifications@github.com> wrote:

it's all there, nto make sense check twice bpf no? the rest is the same

        if bpf:
            if remote:
                pargs.extend(["and", "("] + bpf.split(' ') + [ ")" ] )
            else:
                pargs.extend(["and", "(", bpf, ")" ] )

        if remote:
            pargs.extend(["'"])

**Comment by doomedraven** [comment]
or that is incomplete or im blind :P, can you point me where is different, teh fiel_path not count

it checks first if is bpf, if no, it not do nothing for local neither remote
so the rest is the same looks for me

```
cuckoo@cape-01:~$ diff -uN sniffer.py sniffer2.py
--- sniffer.py  2018-09-17 21:34:28.766113006 +0000
+++ sniffer2.py 2018-09-17 21:35:06.637637876 +0000
@@ -31,7 +31,7 @@
         if remote:
             file_path = "/tmp/tcp.dump.%d" % self.task.id
         else:
-            file_path = os.path.join(CUCKOO_ROOT, "storage", "analyses", str(self.task.id), "dump.pcap")
+            file_path = os.path.join(CUCKOO_ROOT, "storage", "analyses","%s" % self.task.id, "dump.pcap")
         host = self.machine.ip
         # Selects per-machine interface if available.
         if self.machine.interface:
@@ -104,11 +104,14 @@
                       "not", "(", "src", "host", resultserver_ip, "and",
                       "src", "port", resultserver_port, ")"])
 
-        if remote and bpf:
-            pargs.extend(["and", "("] + bpf.split(' ') + [ ")" ] )
+        if bpf:
+            if remote:
+                pargs.extend(["and", "("] + bpf.split(' ') + [ ")" ] )
+            else:
+                pargs.extend(["and", "(", bpf, ")" ] )
+
+        if remote:
             pargs.extend(["'"])
-        elif bpf:
-            pargs.extend(["and", "(", bpf, ")"])
 
         if remote and not remote_host:
             log.exception("Failed to start sniffer, remote enabled but no ssh string has been specified")
```

**Comment by doomedraven** [comment]
amazing, works

**Pull request closed without merging**
