### PR TITLE
Sniffer indent

### PR DESCRIPTION
**Pull request by redsand**
See https://github.com/ctxis/CAPE/pull/113

This should be a fix for this issue

### CODE REVIEW

**Comment by redsand** [comment]
@doomedraven hey bud, mind testing this for me? should fix all the indent issues.

**Comment by doomedraven** [comment]
The indent isnt the core problem but later i can test it, the problem what that still wont work with local sniffing

**Comment by doomedraven** [comment]
is what we was speaking about this morning

**Comment by doomedraven** [comment]
tcpdump <defunc> im checking how to fix it

**Comment by doomedraven** [comment]
this is original sniffer
https://github.com/ctxis/CAPE/pull/113/files

now compare that to your

**Comment by redsand** [comment]
Actually that is not true.  Here is the diff from my patch and the
origional sniffer file.  I'm not sure where you got your file from.

https://github.com/ctxis/CAPE/commit/2e6c14e12810f630b1defc761b29462b9f423568

Tim

**Comment by doomedraven** [comment]
idk, see this sniffer was touched only by you https://github.com/ctxis/CAPE/commits/master/modules/auxiliary/sniffer.py

**Comment by doomedraven** [comment]
well taht is not important, the important is what is time to us to fix it and forget ;)

**Comment by redsand** [comment]
Hang on.  Again I ask where you got your sniffer.py file.

Here is the original file from the initial commit:
https://github.com/ctxis/CAPE/blob/c10004f3f7d4dd2e8a93c726020cf5df325b2717/modules/auxiliary/sniffer.py

There is no "def init"

Please advise

**Comment by doomedraven** [comment]
i tihnk i found fix

**Comment by doomedraven** [comment]
ok that isn't your fault, i don't blame you just that was introduced by em on cuckoo-mod as if that isn't exit self.proc can generate problems

anyway i found problem with sniffer, can you discart with your pr? here so @kevoreilly can merge the rest of the stuff, and i will pr with fixed sniffer, for local and should be fine for remote, i will ask you for test it before merge is that is ok for you?

**Comment by redsand** [comment]
Yes, sounds good.  No worries over here. no emotions, lol.  I was just
getting confused and frustrated trying to track down the source of the
facts of the problem.

You're freakin awesome spending time helping me.  I really appreciate it.
I'll cancel the pr now. stand by

**Comment by doomedraven** [comment]
no, you don't need to close it, only discard changes to sniffer :), can you push the rest again?

**Comment by redsand** [comment]
Those changes are also found here:
https://github.com/ctxis/CAPE/pull/117/files

**Comment by doomedraven** [comment]
ah great :)

**Pull request closed without merging**
