### PR TITLE
add vba2graph

### PR DESCRIPTION
**Pull request by doomedraven**

### CODE REVIEW

**Comment by doomedraven** [comment]
wait missed deps

**Comment by doomedraven** [comment]
done now :)

**Comment by kevoreilly** [comment]
Got any good samples to test on? :)

**Comment by doomedraven** [comment]
try any of this https://github.com/MalwareCantFly/Vba2Graph/tree/master/Examples
the filename hash is the sample hash, im doing small PR to remove useless loging

**Comment by doomedraven** [comment]
can you test this one? 0f0ea7871bc89a56ccb958cbfc47754b
for some reason i have problem with mongo, but i don't add nothing to results

**Comment by doomedraven** [comment]
ok that isn't related, just commented out code and still fails

**Comment by doomedraven** [comment]
pushed fixes https://github.com/ctxis/CAPE/pull/94

**Comment by doomedraven** [comment]
confirmed, now works just fine :)

**Comment by kevoreilly** [comment]
Am testing this now - have found a test for 'HAS_OLETOOLS' on line 1092 of static.py but this variable is never set anywhere as far as I can tell...

**Comment by doomedraven** [comment]
yep, i renamed that to HAVE_OLETOOLS, i was renamed that, as the rest is HAVE not HAS, that should be replaced, pushing

**Comment by kevoreilly** [comment]
Thanks for that. Another little niggle:

$ sudo pip install graphviz
Requirement already satisfied: graphviz in /usr/local/lib/python2.7/dist-packages (0.9)

But...

$ dot
The program 'dot' is currently not installed. You can install it by typing:
sudo apt-get install graphviz

With no dot, the vba2graph_gen fails with:

[modules.processing.static] INFO: [Errno 2] No such file or directory

This corresponds to line 938:

    process = Popen(['dot', '-Tpng', dot_output_path, '-o', png_output_path])

This is fixed by installing graphviz using apt-get, but it might be worth making a note of this requirement or adding some error handling to the Popen call in case it fails for this reason. 

But other than that it works! And looks fantastic :)

**Comment by doomedraven** [comment]
adding it :)

**Comment by kevoreilly** [comment]
It will soon be time for a tweet to show the world this awesome feature! Thanks a lot to both you and @MalwareCantFly!

**Comment by doomedraven** [comment]
are are welcome :P

**Comment by doomedraven** [comment]
cool thanks, that will make it easier to integrate it to more nice tools :)

**Comment by kevoreilly** [comment]
mo' problems! can't seem to get this wrapped up!

Traceback (most recent call last):
  File "/cape/cape/utils/../lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/cape/cape/utils/../modules/processing/static.py", line 1508, in run
    static = Office(self.file_path, self.results).run()
  File "/cape/cape/utils/../modules/processing/static.py", line 1213, in run
    results = self._parse(self.file_path)
  File "/cape/cape/utils/../modules/processing/static.py", line 1157, in _parse
    iocs = vbadeobf.parse_macro(vba_code)
  File "/cape/cape/utils/../lib/cuckoo/common/office/vbadeobf.py", line 180, in parse_macro
    substituted = handle_techniques(line, **opts)
  File "/cape/cape/utils/../lib/cuckoo/common/office/vbadeobf.py", line 122, in handle_techniques
    line = re.sub(r'(?i)((?:Chr[A-Z$]?\(\d+\)\s*&?\s*)+)', decode_chr, line)
  File "/usr/lib64/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/cape/cape/utils/../lib/cuckoo/common/office/vbadeobf.py", line 38, in <lambda>
    return lambda *args: '"""' + f(*args) + '"""'
  File "/cape/cape/utils/../lib/cuckoo/common/office/vbadeobf.py", line 53, in decode_chr
    return "".join(chr(int(n)) for n in ascii)
  File "/cape/cape/utils/../lib/cuckoo/common/office/vbadeobf.py", line 53, in <genexpr>
    return "".join(chr(int(n)) for n in ascii)
ValueError: chr() arg not in range(256)

This is on 2eb3c9502d68b32862144a095d00a673f58b8258e7d2890bcb3fac25411d90a0 - problems with vbadeobf now somehow... :(

**Comment by doomedraven** [comment]
testing

**Comment by doomedraven** [comment]
```
dFWtF = zmmBj - Cos(ctHtab) * 1 - Chr(11530) / 97178 - ChrB(TsSIlw)
zZZSE = 59273
uwKVBA = pnvvu - Cos(cLbUE) * 1 - Chr(13037) / 61656 - ChrB(NDlTM)
mMbOtz = 93703
AOnVBYMBvTC = kOBowZZrP + aSqsqMVbb + tKRHitsFj + NDNVs + dFJzmHm + CGszKA + iKinzBhPkK + wiSRCvInc + BLftDFTsdRU
uPGEw = dEXMr - Cos(lozFNz) * 1 - Chr(97617) / 74904 - ChrB(vZBoPc)
MjBwJQ = 32851
End Function
Sub Autoopen()
On Error Resume Next
OzINj = jYcUw - Cos(OVAvwJ) * 1 - Chr(61666) / 98566 - ChrB(EQjqAs)
LviVXm = 83710
EFNIR (AOnVBYMBvTC)
plGYO = ZTQiO - Cos(fGzAjR) * 1 - Chr(40041) / 19442 - ChrB(ZWfPqN)
mdacdm = 12222
End Sub
Function EFNIR(hBrfDFE)
On Error Resume Next
DHkpi = SMmBKE - Cos(ilFRhf) * 1 - Chr(31444) / 28092 - ChrB(IXotjn)
lMtzk = 94221
jffkGK = NfIjEr - Cos(KwGqw) * 1 - Chr(54272) / 97357 - ChrB(BlRfJ)
pRFMl = 17955
WzmUfvbCSQA = Shell(tzhROzOl + Chr(vbKeyP) + RLZAzJ + hBrfDFE, vbHide)
mBuJE = usfJcv - Cos(aQmJlU) * 1 - Chr(57372) / 38614 - ChrB(uTbAtY)
CXTiw = 47379
End Function

ERROR:modules.processing.static:chr() arg not in range(256)
2018-09-07 16:54:42,478 [modules.processing.static] ERROR: chr() arg not in range(256)
```

i think that just getting chr(.+) instead of do all that operations as macro does, i have added try_except here and at least can get the rest of info

**Comment by MalwareCantFly** [comment]
Just to make sure:
You are running "olevba --deobf" in order to show more info in Static analysis?
It won't make any difference for Vba2Graph...

**Comment by doomedraven** [comment]
nop, i was thinking about add it, but i will need to do more testing

**Comment by MalwareCantFly** [comment]
So why is @kevoreilly getting deobf errors? :\

**Comment by doomedraven** [comment]
because there is lib oledeobf.parse_macro, and it do their own deobf

**Comment by kevoreilly** [comment]
Thanks for looking into it, I probably should have put it in a different thread, nothing to do with vba2graph! I was just eager to get a tweet out about the new graphs before the weekend but it will wait :)

**Comment by doomedraven** [comment]
We need to add option to download png/svg/etc as i got once so width that was insane will do it when will be back in town

**Pull request merged**
