### PR TITLE
Create signature for cryptomining

### PR DESCRIPTION
**Pull request by kevross33**

### CODE REVIEW

**Comment by doomedraven** [comment]
check my sig in cuckoo v2 prs to extend this one ;)

**Comment by kevross33** [comment]
MD5s 60e2d72599a522135bfa17bba8be4971 & 0328cd8c27fed8143f5fbda71e7924fe

More info here https://blog.talosintelligence.com/2018/01/malicious-xmr-mining.html

image

**Comment by kevross33** [comment]
wow fast response doomedraven :-) will check it out

**Comment by kevross33** [comment]
which is the sig you are refering to?

**Comment by doomedraven** [comment]
see based on :)
https://github.com/cuckoosandbox/community/pull/375

**Comment by kevross33** [comment]
Ah cool. I thought you meant extensions to the commandline. I was thinking of adding a sig like this so i will convert and add when I have some time as I need to check lists of monero domains to add any too. Thanks.

**Comment by doomedraven** [comment]
in my opinion it would be neat to have all in one, as they are pretty small, instead of have tons of few lines sigs

**Comment by kevoreilly** [comment]
Thanks guys!

**Pull request merged**
