### PR TITLE
restore original sniffer.py, if someone wants remote, first fix it to…

### PR DESCRIPTION
**Pull request by doomedraven**
… work for both versions :)

### CODE REVIEW

**Comment by redsand** [comment]
Can you tell me the other version?

I only have access to a kvm deployment

**Comment by redsand** [comment]
Side note, I'd rather press forward and add the additional support, rather than roll back. But that's my two cents.

**Comment by doomedraven** [comment]
the additional support is good, the problem is what that is totally broken, it tried to fix it yesterday, there was a problem with indentation, etc, all was fixed, but no that doesn't work. i also have kvm here. what do  you mean another version? of sniffer? it is in repo right now `modules/auxiliar/sniffer.py`

**Comment by redsand** [comment]
I think I know what you mean... when you said "first fix it to support both
versions", you're referring to python 2 and python 3?

If so, I'd be happy to fix indents for compatibility and to test it. My dev
and testing has all been py2.7

Please confirm.

Tim

**Comment by doomedraven** [comment]
no, i mean for local and remote sniffing :)
as local sniffer doesn't work

**Comment by redsand** [comment]
Ohhhh ok.   I need an env to test. I only have Kvm remote environment
currently. I thought I separated the conditions but guess not. I can review
the code tomorrow

**Comment by doomedraven** [comment]
would de good, i tried do quick fixes, but no way, be careful with spaces and tabs you have mixed them and if you check code there are indent problems also

but so far i don't know who else use it so basically who need remote should fix it :P

**Comment by redsand** [comment]
You got it. I'm on it. So bossy, lol. :-)

**Comment by doomedraven** [comment]
let me know if you need any help :)

**Comment by doomedraven** [comment]
and thanks

**Comment by redsand** [comment]
Im kidding, bud. Lol. 

I’ll let you know when I’ve got a fix and have you QA it for me. 

Thanks a lot for finding this. 

Tim

On Sep 17, 2018, at 2:13 AM, doomedraven <notifications@github.com> wrote:

and thanks

**Comment by doomedraven** [comment]
ok fixed on my side

**Pull request closed without merging**
