### PR TITLE
fixed few typos

### PR DESCRIPTION
**Pull request by marirs**
1. fixed typos of writing to .log while looking for .xml
2. Instead of writing the events every 15seconds, write events when Aux Module Stops at 1 go.
3. Removed threading as it wasnt necessary

Note: Make sure that sysmon.exe is downloaded and installed as service in the guest for this to even work.

### CODE REVIEW

**Comment by doomedraven** [comment]
changes to sysmon will break it as you changed start and stop

**Comment by marirs** [comment]
like I mentioned - I removed Threading as it wasnt necessary at all. Hence the start/stop

**Comment by doomedraven** [comment]
yes but that breaks the initial idea, it should collect logs every x time, bcz they can do their stuff and wipe logs, so in that way you can get at least something or something breaks so you have part of logs anyway

**Comment by marirs** [comment]
Ahh.. I missed that part.. Allright then, you need to then change the write to .xml and not .log...

**Comment by doomedraven** [comment]
well that is just extension how it dump, but the data inside are xml format

**Comment by doomedraven** [comment]
read this, https://github.com/ctxis/CAPE/blob/master/modules/processing/sysmon.py this process that file, so it get log just fine

**Comment by marirs** [comment]
From the Windows Guest - What are you trying to upload to host? 
The collect_logs routine, creates a .log file as the output of collecting the event logs, but when you are doing a upload_to_host, you are checking to see if there is a c:\sysmon.xml and not c:\sysmon.log

**Comment by doomedraven** [comment]
i don't see in any moment the sysmon.log it always .xml, so which is the problem?

```
    def collect_logs(self):
        try:
            subprocess.call(["C:\\Windows\\System32\\wevtutil.exe", "query-events",
                             "Microsoft-Windows-Sysmon/Operational", "/rd:true", "/e:root",
                             "/format:xml", "/uni:true"], startupinfo=self.startupinfo,
                            stdout=open("C:\\sysmon.xml", "w"))
        except Exception as e:
            log.error("Could not create sysmon log file - %s" % e)

        # Give it some time to create the file
        time.sleep(5)

        if os.path.exists("C:\\sysmon.xml"):
            upload_to_host("C:\\sysmon.xml", "sysmon/%s.sysmon.xml" % time.time())
        else:
            log.error("Sysmon log file not found in guest machine")
```

**Comment by marirs** [comment]
just made a pull request with the fix.. :)

**Comment by doomedraven** [comment]
ok i think i found where i got confused, i was looking your code and not original one, too much context to switch frequently, that new PR make sense, but not this one :P

**Comment by marirs** [comment]
absolutely... will close this one :)

**Pull request closed without merging**
