### PR TITLE
Update ransomware_files.py

### PR DESCRIPTION
**Pull request by ditekshen**
Added new and some old known ransomware files.

### CODE REVIEW

**Comment by doomedraven** [comment]
nice one! thanks

**Comment by kevoreilly** [comment]
Very much appreciated :-)

**Comment by doomedraven** [comment]
@kevoreilly  can you test it on your side? one friend tol that breaks 
photo_2019-08-13_20-27-50

**Comment by ditekshen** [comment]
Interesting. I have updates in place for almost 2 weeks and haven't encountered this before. I will double check from my side as well.

**Comment by doomedraven** [comment]
did you try with re2? 
```
    apt-get install libre2-dev -y
    pip install re2
```

that is used if installed, that gives a huge performance improvement, and as you can see it fails on it

**Comment by ditekshen** [comment]
I don't have re2 installed. Looking at the error message, there is this "invalid character class range: \Pr", and there is only one entry in the list that appears similar, in terms of the "\Pr":

("C:\\ProgramData\\\.FreezedByMagic.LOG$", ["FreeMe"]),

If the above line is removed, would it run without errors?

**Comment by doomedraven** [comment]
well i think if you use it like `r"C:\ProgramData\.FreezedByMagic.LOG$",` or `"C:\\ProgramData\\.FreezedByMagic.LOG$",` it should works, i can't test it rigth now, that is from my friend

**Comment by ditekshen** [comment]
Currently, it is defined as below:
```
"C:\\ProgramData\\\.FreezedByMagic.LOG$"
```

**Comment by doomedraven** [comment]
hm well once i will be able to test it i will let you know, but thanks for colaboration :)

**Comment by ditekshen** [comment]
Not a problem at all. I, too don't have a dev box handy at the moment, otherwise I would have installed re2 and tested it. Please let me know if you catch that error and I will try to fix it.

**Comment by doomedraven** [comment]
yes it was, instead of \\ it was needed \\\\ to escape themselves, pr pushed

**Pull request merged**
